name: Test Workflow
  
on:
  workflow_dispatch:
  push:
    branches:
      - posts
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Print Hello
        run: echo "Wello hold!?"
